SUPABASE_URL = "https://lbglnxnrisujcwdqyjtv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZ2xueG5yaXN1amN3ZHF5anR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1Nzc3NjksImV4cCI6MjA4NTE1Mzc2OX0.OgoJlfv3TGMigBZDhCGbz5_FsyQvmwr_kVDy5_qSkGU"
